# Generated by Django 3.2.9 on 2021-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=100)),
                ('mercado', models.DateField()),
                ('valor_compra', models.DateField()),
                ('data', models.DateField()),
                ('entidade', models.CharField(max_length=100)),
                ('tipos_notas', models.TextField(choices=[('CUPO', 'Cupom Fiscal'), ('NOTA', 'Nota Fiscal')], default=0, max_length=4)),
            ],
        ),
    ]
